/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:24f2d29e-68b9-49a3-94c7-05c60273a7fb",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_kqM6dFbZh",
    "aws_user_pools_web_client_id": "67pi556t9pfrr4dhavmgsi53aj",
    "oauth": {},
    "aws_user_files_s3_bucket": "bookstoref30d82e2a6134f61914c3688120e9ac4152722-prod",
    "aws_user_files_s3_bucket_region": "us-west-2",
    "aws_appsync_graphqlEndpoint": "https://nac73aredjb5vm5lxg355wwifq.appsync-api.us-west-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-west-2",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_appsync_apiKey": "da2-qywfoclnr5au5jijsinuvr4af4"
};


export default awsmobile;
